fix for resuming video in kaltura after getting in foreground mode fr…
applicaster/Zapp-Frameworks pull request #1055
Opened 2022-07-06 12:13 UTC by ikozlov-sc

…om background

## Description

[Monday ticket](https://applicaster.monday.com/boards/1615228456/pulses/2834693911)

`Hey! Please draw your attention that description of the ticket is wrong. When the user moves to the background mode and then returns back to the foreground - player doesn't resume after pausing in background. 

**_Expected behaviour and hot it works after fix_**: User is on the app, video plays -> User moves to background mode( for example goes to desktop with different apps -> User is in background and video pauses -> User open the app, video resumes and plays as before moving into a background mode`

_**How it was before fixing:**_ user is in the app, video plays -> User moves to background mode( for example goes to desktop with different apps -> User is in background and video pauses -> User open the app and video doesn't play.

@kononenkoAnton I assigned you as assignee cause of your worked with this files, maybe it can be useful for review. Thanks.

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [+ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

2022-07-07 07:45 UTC, snooky23 requested changes

2022-07-07 07:45 UTC, snooky23 commented on plugins/quick-brick-kaltura-player/apple/universal/View/Player+Notification.swift
> +        defaultCenter.addObserver(self,
Please check that you are removing all the observers upon deinit.

2022-07-14 08:25 UTC, ikozlov-sc commented on plugins/quick-brick-kaltura-player/apple/universal/View/Player+Notification.swift
> +        defaultCenter.addObserver(self,
Avi, I checked and everything is okay and ready for merging. There's a line in code which deletes all observers `NotificationCenter.default.removeObserver(self)` , also since iOS 9.0 we doesn't need to remove observes which is not block-based. It can be merged.

2022-07-18 07:54 UTC, snooky23 approved these changes

2022-07-18 07:54 UTC, merged