feat: wip: support disable for firebase
applicaster/Zapp-Frameworks pull request #107
Opened 2020-11-03 21:33 UTC by inckie

Disable auto start for messaging
Add support for run-time enable-disable operations for the plugin

2020-11-04 23:07 UTC, ranmeirman requested changes

2020-11-04 23:07 UTC, ranmeirman commented on plugins/zapp-push-plugin-firebase/android/src/main/AndroidManifest.xml
> +        <meta-data
Any particular reason why you decided to use manifest const?

2020-11-04 23:07 UTC, ranmeirman commented on plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/FirebasePushProvider.kt
> +    override fun disable(): Boolean {
Is this always fire and forget? Shouldn't we allow passing a listener in case someone want to know it failed or succeeded?

2020-11-05 14:50 UTC, inckie commented on plugins/zapp-push-plugin-firebase/android/src/main/AndroidManifest.xml
> +        <meta-data
It's easier, plus we don't get a change to execute any code when plugin is disabled. And this setting is most important in disabling. Also, there are move lines next to it setting up other firebase stuff not available from code: default channel and icon.

2020-11-05 14:56 UTC, inckie commented on plugins/zapp-push-plugin-firebase/android/src/main/java/com/applicaster/firebasepushpluginandroid/FirebasePushProvider.kt
> +    override fun disable(): Boolean {
I though about it, but it will require changes in plugin manager, we will need to push it through new interface for enabling, and there are some ambiguity:
- when we doing batch disable, we will only have 1 high level callback, or we will need 2 arguments: failed and succeeded ids or something
- plugin is marked disabled in manager instantly, but still performing disable work, but calling code not always can wait for it. We will need something like reactive observable everywhere
- and most important: plugin enabling is takes time too, but we do not have any interface and means of control on app startup. Example is UAH: we don't wait for it to take off. So if we add an option to wait, we need to refactor application initialization sequence probably as well.
Its a nice feature, but we need to do it for all plugins in both init and disable

2020-11-12 20:05 UTC, ranmeirman approved these changes

2020-11-12 20:15 UTC, merged