fix for auto play after player was applied on the screen after scroll…
applicaster/Zapp-Frameworks pull request #1079
Opened 2022-07-18 09:08 UTC by ilyaKozlovApplicaster

…ing.

## Description

[Monday ticket](https://applicaster.monday.com/boards/1615228456/pulses/2779387230)

`Guys, now I found out that there's a bug with viewport. Video's not playing after appearing player after scrolling, just it was in pause state, yet it must play.I fixed it and prepare this PR.`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [+ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

2022-07-18 12:38 UTC, alexzchut requested changes

2022-07-18 12:38 UTC, alexzchut commented on plugins/quick-brick-kaltura-player/apple/universal/ViewController/KalturaPlayerViewController.swift
> +            super.viewWillDisappear(animated)
super.viewWillAppear

2022-07-18 12:42 UTC, snooky23 requested changes

2022-07-18 12:42 UTC, snooky23 commented on plugins/quick-brick-kaltura-player/apple/universal/ViewController/KalturaPlayerViewController.swift
> +            player?.play()
I don't think it's the right way to go here. 
What if the user paused the video before going to the background?

2022-07-18 12:44 UTC, ilyaKozlovApplicaster commented on plugins/quick-brick-kaltura-player/apple/universal/ViewController/KalturaPlayerViewController.swift
> +            player?.play()
It's a good note from you and Alex regarding flag. I will update it with flag and changesuper.viewWillDisappear(animated) to super.viewWillAppear(animated) .

2022-07-20 07:40 UTC, ilyaKozlovApplicaster reviewed
@snooky23 @alexzchut I added a flag which keep state of the player. I marked it as private because of this flag must works only within controller class and it's responsible only for keeping state of state. I tested and it works as expected as when player is initially plays and also when it's initially paused. P.s. It's not possible to work with state via observers calls cause of view controller life cycle methods work faster.

2022-07-21 09:17 UTC, alexzchut requested changes

2022-07-21 09:17 UTC, alexzchut commented on plugins/quick-brick-kaltura-player/apple/universal/ViewController/KalturaPlayerViewController.swift
> +            if player?.rate == 0 { // check either player is paused
this if/else can be replaced with:
`isPausedBeforeDisapearing = player?.rate == 0`

2022-07-21 09:17 UTC, alexzchut commented on plugins/quick-brick-kaltura-player/apple/universal/ViewController/KalturaPlayerViewController.swift
> +            if !isPausedBeforeDisapearing, player?.rate == 1 {
I think this is not needed because isPausedBeforeDisapearing should be updated to false on every call of viewWillAppear

2022-07-21 09:17 UTC, alexzchut commented on plugins/quick-brick-kaltura-player/apple/universal/ViewController/KalturaPlayerViewController.swift
> +        }
reset the isPausedBeforeDisapearing value after using it

2022-08-14 13:20 UTC, alexzchut approved these changes

2022-08-14 19:42 UTC, snooky23 approved these changes

2022-08-14 20:16 UTC, inckie commented
In theory this logic should be much higher, since there is no guarantee that when view returns to viewport it still should play (its probably hard to get into that state now though, maybe only with 2 cell player views at same time on feed, until we can not primary type of player without leaving the screen), and there can be other edge cases, so there will be either more flags needed. If we move this logic higher to where overall orchestration happens, it will be in one place, and will be easy to customize later. Low level API should just inform some controller (now its player manager) that it left the viewport or entered it, and PM will make the call taking other things into consideration.

2022-08-18 08:26 UTC, merged