chore: create new plugin zapp analytics plugin brightcove
applicaster/Zapp-Frameworks pull request #1250
Opened 2022-11-14 16:59 UTC by kononenkoAnton

## Description

[Monday ticket](add your monday ticket url here)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2022-11-21 07:31 UTC, alexzchut requested changes

2022-11-21 07:31 UTC, alexzchut commented on plugins/zapp-analytics-plugin-brightcove/apple/ZappAnalyticsPluginPlayer.podspec.json
> +    "OTHER_CFLAGS": "-fembed-bitcode"
remove line 27 and line 25

2022-11-21 07:31 UTC, alexzchut commented on plugins/zapp-analytics-plugin-brightcove/manifests/manifest.config.js
> +  ios_for_quickbrick: "6.0.0-Dev",
6.3.0-Dev

2022-11-21 07:31 UTC, alexzchut commented on plugins/zapp-analytics-plugin-brightcove/manifests/manifest.config.js
> +  tvos_for_quickbrick: "6.0.0-Dev",
6.3.0-Dev

2022-11-23 17:41 UTC, inckie commented
On Android I see wrong deviceType `deviceType=other`
Also I see duration reported with dot, hope backend will work with that `video_duration=154529.0`

2022-11-30 20:58 UTC, inckie approved these changes

2022-11-30 21:33 UTC, merged