feat: Update version of OneTrust CMP provider to 202210.1.0.0
applicaster/Zapp-Frameworks pull request #1258
Opened 2022-11-20 09:51 UTC by alexzchut

## Description
Update version of OneTrust CMP provider to 202210.1.0.0
https://developer.onetrust.com/onetrust/docs/changelog-ios-tvos#20221010

[Monday ticket] https://applicaster.monday.com/boards/2742545177/pulses/3540944306

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2022-11-23 14:54 UTC, ranmeirman requested changes

2022-11-23 14:54 UTC, ranmeirman commented on plugins/applicaster-cmp-onetrust/manifests/manifest.config.js
> +    tooltip_text: "Onetrust SDK path or version to use with the app",
why should it be path? let's only use version, it is confusing.

2022-11-23 17:41 UTC, alexzchut commented
@ranmeirman I updated the label, please review again

2022-11-23 20:09 UTC, ranmeirman commented on plugins/applicaster-cmp-onetrust/manifests/manifest.config.js
> +    initial_value: "",
We don't want a default value? Also let's add, "OneTrust requires that the version set in this field to match the SDK version published on the OneTrust portal. In case the versions will not match the OneTrust screen will not work properly".

2022-11-23 22:08 UTC, alexzchut commented on plugins/applicaster-cmp-onetrust/manifests/manifest.config.js
> +    initial_value: "",
@ranmeirman 
There is a fallback to the version specified in plugin (on iOS/tvOS it is on podspec) so if no value added here, it will take the predefined tested version. Basically we can put the same predefined version here to let the user know what is it and let him change if needed.
I will change the description

2022-11-23 22:14 UTC, alexzchut commented on plugins/applicaster-cmp-onetrust/manifests/manifest.config.js
> +    initial_value: "",
Having the version specified also here as default value will actually require a need of updating it in several places and in addition it can be different for each platform

2022-11-23 22:24 UTC, alexzchut commented on plugins/applicaster-cmp-onetrust/manifests/manifest.config.js
> +    tooltip_text: "OneTrust requires that the version set in this field to match the SDK version published on the OneTrust portal. In case the versions will not match the OneTrust screen will not wor
@ranmeirman I added the initial value based on the platform so it is defined below for each one like we have on sdks

2022-11-23 22:24 UTC, alexzchut commented on plugins/applicaster-cmp-onetrust/manifests/manifest.config.js
> +
here

2022-11-23 22:48 UTC, alexzchut commented
@ranmeirman I updated the tooltip and also added the default values per platform that will be set on plugin, we will keep in mind to update these values if needed, FYI @inckie

2022-11-24 04:51 UTC, ranmeirman approved these changes
From the manifest perspective it is approved, the rest should be reviewed by someone that knows more the details.

2022-11-24 13:54 UTC, mmatsuk-sc commented
Native part is finished, i guess. Need to review it with Alex. I also think configuration property `show_intro_screen` could be removed from the native side config. It will be used for the web platforms only

2022-11-28 17:56 UTC, inckie approved these changes

2022-11-28 17:56 UTC, merged