chore(quick-brick-user-account-ui-component): add screen resolver to user account component
applicaster/Zapp-Frameworks pull request #1265
Opened 2022-11-22 17:10 UTC by kononenkoAnton

## Description

[Monday ticket](add your monday ticket url here)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2022-11-22 19:34 UTC, ranmeirman requested changes

2022-11-22 19:34 UTC, ranmeirman commented on plugins/quick-brick-user-account-ui-component/manifests/styles.config.js
> +          "Add screen mapping login_{{ctx/countryCode}}in this format, fallback logic",
@kononenkoAnton I don't understand the tooltip and also you are missing space before the `in`

2022-11-22 19:34 UTC, ranmeirman commented on plugins/quick-brick-user-account-ui-component/manifests/styles.config.js
> +          { text: "Login resolver", value: "login_resolver" },
Please change the label to `Type Mapping Resolver`

2022-11-22 19:34 UTC, ranmeirman commented on plugins/quick-brick-user-account-ui-component/manifests/styles.config.js
> +        tooltip: "Add screen mapping login_{{ctx/countryCode}}in this format",
same comment as above

2022-11-22 19:34 UTC, ranmeirman commented on plugins/quick-brick-user-account-ui-component/manifests/styles.config.js
> +          "Add screen mapping login_{{ctx/countryCode}}in this format, fallback logic",
same comment as above

2022-11-22 19:34 UTC, ranmeirman commented on plugins/quick-brick-user-account-ui-component/manifests/styles.config.js
> +          "Add screen mapping login_{{ctx/countryCode}}in this format, fallback logic",
same comment as above

2022-11-22 19:34 UTC, ranmeirman commented on plugins/quick-brick-user-account-ui-component/manifests/styles.config.js
> +        tooltip: "Add screen mapping login_{{ctx/countryCode}}in this format",
same comment as above

2022-11-22 19:34 UTC, ranmeirman commented on plugins/quick-brick-user-account-ui-component/manifests/styles.config.js
> +          "Add screen mapping login_{{ctx/countryCode}}in this format, fallback logic",
same comment

2022-11-29 19:06 UTC, inckie approved these changes

2022-11-29 20:02 UTC, ranmeirman approved these changes

2022-11-29 20:14 UTC, merged