fix(brightcove-analytics): crash on no accountid
applicaster/Zapp-Frameworks pull request #1360
Opened 2023-01-27 18:57 UTC by seftonmonk

Brightcove analytics was crashing when there is no account id.

[Monday ticket](https://applicaster.monday.com/boards/1615228456/pulses/3877161102)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2023-01-27 19:02 UTC, kononenkoAnton requested changes
this.accountId will be always null, since `prepareData` inside `BrightcoveEventsFactory` will be called only when event will be created.

2023-01-27 19:25 UTC, seftonmonk commented
> this.accountId will be always null, since `prepareData` inside `BrightcoveEventsFactory` will be called only when event will be created.

onTimeUpdate seems to be called outside of to the scope of config

2023-01-27 20:07 UTC, inckie requested changes

2023-01-27 20:07 UTC, inckie commented on plugins/zapp-analytics-plugin-brightcove/src/index.ts
> +      log_warning("onTimeUpdate: no entry found");
add return there, and remove else, so we will have easy to read linear code:

- check something and quit
- check something else and quit
- do usefull part

2023-01-27 20:09 UTC, kononenkoAnton requested changes

2023-01-27 20:09 UTC, kononenkoAnton commented on plugins/zapp-analytics-plugin-brightcove/src/index.ts
> +    if (!id) {
Better to `return` function after if and not use `else` code will be more readable
```
 if (!id) {
       log_warning("onTimeUpdate: no entry found");
      return 
     }
....
```

2023-01-27 20:09 UTC, kononenkoAnton commented on plugins/zapp-analytics-plugin-brightcove/src/index.ts
> +    getAccountId().then((accountId) => {
I would move it to separate function from the constructor, because for DOM you probably will not have a session storage in account id. So you have to also do this check for DOM function that is using function
`initialize = (config: BrightcoveConfig = null)` to initialize  
```
  getAccountId().then((accountId) => {
       if (accountId) {
         playerManager.on("timeupdate", this.onTimeUpdate);
       }
     });
```
So it should be called from `constructor` and from `initialize`. Just make sure that initialize is not calling on native, so you will not observer two times

2023-01-30 14:40 UTC, seftonmonk commented on plugins/zapp-analytics-plugin-brightcove/src/index.ts
> +    getAccountId().then((accountId) => {
@kononenkoAnton is initialize function even being used?

2023-01-30 18:55 UTC, kononenkoAnton approved these changes

2023-02-02 19:31 UTC, inckie approved these changes

2023-02-02 19:31 UTC, merged