Feat/context setter web
applicaster/Zapp-Frameworks pull request #1380
Opened 2023-02-15 07:54 UTC by Pretzi

## Description

[Monday ticket](https://applicaster.monday.com/boards/1615228456/pulses/3886109024)

`If merged this will add support to the web platforms in the Context setter plugin`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2023-02-15 16:36 UTC, inckie commented on plugins/zapp-context-setter/src/utils.js
> +  return await sessionStorage.getItem(key, namespace);
both local and session keys can be used, use resolver from QB that reads both storages

2023-02-15 16:48 UTC, inckie commented on plugins/zapp-context-setter/src/utils.js
> +  return await sessionStorage.getItem(key, namespace);
Add todo there, we will migrate it to https://github.com/applicaster/Zapp-Frameworks/blob/master/plugins/quick-brick-user-account-ui-component/src/utils/ContextResolver/Resolvers/CTXResolver.ts
in a separate PR after merge

2023-02-15 16:49 UTC, inckie commented on plugins/zapp-context-setter/src/components/StartupHook.js
> +      await setExtraContextKeys(response?.storage_keys);
if its null or empty, do not call setExtraContextKeys so it will not need to deal with nulls

2023-02-15 17:47 UTC, inckie commented on plugins/zapp-context-setter/src/utils.js
> +    const [namespace, key] = match.replace(/[{}]+/g, '').split("/");
oh also part before / is not namespace, its resolver name, can be ctx/ or empty now, both mean storages. Namespace is same dot notation in part after slash as in  https://github.com/applicaster/Zapp-Frameworks/blob/master/plugins/quick-brick-user-account-ui-component/src/utils/ContextResolver/Resolvers/CTXResolver.ts

2023-02-16 11:35 UTC, ranmeirman requested changes

2023-02-16 11:35 UTC, ranmeirman commented on plugins/zapp-context-setter/manifests/manifest.config.js
> +  screen: true,
Why is it a screen?

2023-02-16 11:35 UTC, ranmeirman commented on plugins/zapp-context-setter/manifests/manifest.config.js
> +  preload: true,
I don't think it should support preload, it should be hard coded in the code that it should run on app launch

2023-02-16 14:17 UTC, inckie commented on plugins/zapp-context-setter/manifests/manifest.config.js
> +  preload: true,
@ranmeirman you mean hardcoded from QB side?
Its executed because of require_startup_execution: true now, not sure what preload is

2023-02-16 16:13 UTC, Pretzi commented on plugins/zapp-context-setter/manifests/manifest.config.js
> +  preload: true,
@ranmeirman @inckie preload is required in order to set the plugin as startup hook.

https://github.com/applicaster/QuickBrick/blob/main/packages/quick-brick-core/App/NavigationProvider/NavigationProvider.tsx#L398

2023-02-16 16:13 UTC, Pretzi commented on plugins/zapp-context-setter/manifests/manifest.config.js
> +  screen: true,
No need to be a screen, I removed it.

2023-02-16 16:13 UTC, Pretzi commented on plugins/zapp-context-setter/src/components/StartupHook.js
> +      await setExtraContextKeys(response?.storage_keys);
Done

2023-02-16 16:14 UTC, Pretzi commented on plugins/zapp-context-setter/src/utils.js
> +    const [namespace, key] = match.replace(/[{}]+/g, '').split("/");
Fixed

2023-02-16 16:32 UTC, Pretzi commented on plugins/zapp-context-setter/src/utils.js
> +  return await sessionStorage.getItem(key, namespace);
Done

2023-02-16 16:37 UTC, inckie approved these changes

2023-02-16 17:31 UTC, ranmeirman approved these changes

2023-02-16 17:31 UTC, merged