Pushes ios
applicaster/Zapp-Frameworks pull request #1393
Opened 2023-02-27 10:10 UTC by ilyaKozlovApplicaster

## Description

[Monday ticket](add your monday ticket url here)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [+] iOS

</details>

## Known or Pending Issues

`Earlier customer could send only pushes to user which align to initial topics during first launch. Initial topics come from plugin config. Now customer would like to update topics for pushes in real time. Changes in this PR were did to match customer's wish`

## Version Info

`New version for firebase-push plugin is 6.4.1-alpha.0`

2023-02-27 10:28 UTC, alexzchut requested changes

2023-02-27 10:28 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +                _ = FacadeConnector.connector?.storage?.localStorageRemoveValue(for: Params.Storage.initialTopicsRegistrationProceeded,
why is it needed to check if there is a stored value when you need to store the updated value?

2023-02-27 10:28 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +    lazy var initialTopicsFromPlConfig: [String] = {
please update to `initialTopicsFromPluginConfiguration`

2023-02-27 10:28 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +            .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
use compactMap instead, it will remove a need to filter as it keeps only non-optional values

2023-02-27 10:28 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +            return value.components(separatedBy: ",")
you can use separateComponents that you added below also here to get separated content

2023-02-27 10:28 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +    private func newTopicsWereRegistered(_ topicsToRegister: Set<String>) -> Bool {
there is a func addTagsToDevice that does the same operation and should be used instead, you can refactor it to use async/await but no need to create a new one

2023-02-27 10:28 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +    private func removedTopicWereUnregistered(_ topicsToRemove: Set<String>) -> Bool {
there is a func removeTagsToDevice that does the same operation and should be used instead, you can refactor it to use async/await but no need to create a new one

2023-02-27 10:28 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +        let topicsFromPlgConfigs = Set(initialTopicsFromPlConfig)
please use full names for parameters

2023-02-27 10:28 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +            self.handleInitialTopicsRegistration()
why is it needed to call this on update of all registered topics? update on initial topics should be proceeded on app start, as plugin configuration is not updated during app usage.

2023-02-27 15:56 UTC, ilyaKozlovApplicaster commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +                _ = FacadeConnector.connector?.storage?.localStorageRemoveValue(for: Params.Storage.initialTopicsRegistrationProceeded,
10x. It's a bug.

2023-02-27 16:05 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
> +    private func newTopicsWereRegistered(_ topicsToRegister: Set<String>) -> Bool {
when all tasks are completed it **should not** call initial topics handling again. I saw you added the call to initial topics update when all stored topics are updated and it should not be there..

2023-02-28 13:20 UTC, ilyaKozlovApplicaster commented
@snooky23 @alexzchut all notes were fixed. Can be merged.

2023-03-01 08:40 UTC, snooky23 approved these changes

2023-03-01 08:40 UTC, merged