chore: update readme
applicaster/Zapp-Frameworks pull request #1470
Opened 2023-04-17 09:08 UTC by alashuk-applicaster

## Description
Update README

[Monday ticket](https://applicaster.monday.com/boards/1615228522/views/35072856/pulses/4308708015?userId=17198506)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2023-04-17 10:18 UTC, snooky23 requested changes

2023-04-17 10:18 UTC, snooky23 commented on plugins/quick-brick-matchbox/README.md
>          "PlaceOfGameHeb": "היכל קרפנטייה",
Let's change this key to `gameLocation`. On the datasrouce, lets create create the game location value and keep the old one for now.

2023-04-17 10:18 UTC, snooky23 commented on plugins/quick-brick-matchbox/README.md
>          "TimeOfGame": "15:00",
first letters should be lower case. please adjust for all.

2023-04-17 10:18 UTC, snooky23 commented on plugins/quick-brick-matchbox/README.md
> -        "ExternalID": "0",
What is match status stands for?

2023-04-17 10:18 UTC, snooky23 commented on plugins/quick-brick-matchbox/README.md
>              "isEnabled": false,
Please remove the isEnabled parameters

2023-04-17 10:18 UTC, snooky23 commented on plugins/quick-brick-matchbox/README.md
>      3. `TimeOfGame`;
should be lower case

2023-04-17 12:50 UTC, alashuk-applicaster commented on plugins/quick-brick-matchbox/README.md
>          "TimeOfGame": "15:00",
done

2023-04-17 12:50 UTC, alashuk-applicaster commented on plugins/quick-brick-matchbox/README.md
> -        "ExternalID": "0",
Depends on match status we can see different types of content (past/live/future)

2023-04-17 12:50 UTC, alashuk-applicaster commented on plugins/quick-brick-matchbox/README.md
>              "isEnabled": false,
done

2023-04-17 12:50 UTC, alashuk-applicaster commented on plugins/quick-brick-matchbox/README.md
>      3. `TimeOfGame`;
done

2023-04-19 18:52 UTC, snooky23 requested changes

2023-04-19 18:52 UTC, snooky23 commented on plugins/quick-brick-matchbox/README.md
> -        "ExternalID": "0",
@alashuk-applicaster can you please add this also to the readme? please write all the possible values we can use.

2023-04-20 13:17 UTC, alashuk-applicaster commented on plugins/quick-brick-matchbox/README.md
> -        "ExternalID": "0",
done

2023-05-22 09:31 UTC, snooky23 approved these changes

2023-09-05 08:27 UTC, closed without merging