chore: move info component to Zapp-Frameworks repo
applicaster/Zapp-Frameworks pull request #1471
Opened 2023-04-17 13:09 UTC by alashuk-applicaster

## Description
Move qb-info-component to Zapp-Frameworks repo.
[Monday ticket](https://applicaster.monday.com/boards/1615228456/views/35072856/pulses/4308722726?userId=17198506)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2023-04-17 13:18 UTC, inckie approved these changes

2023-04-17 13:19 UTC, inckie commented
THis should be just new pipesv2:// data source provider, then returns description, then we can use existing cell styles to display it and even handle click if needed (to write to support or copy info for example)

2023-04-20 12:38 UTC, ranmeirman requested changes

2023-04-20 12:38 UTC, ranmeirman commented on plugins/quick-brick-info-component/manifests/android_for_quickbrick.json
> +  "name": "Info component",
@alashuk-applicaster let's change the name to "Version Info Component" - no need for the QB.

2023-04-20 13:07 UTC, alashuk-applicaster commented on plugins/quick-brick-info-component/README.md
> +# QB Info Component
done

2023-04-20 13:07 UTC, alashuk-applicaster commented on plugins/quick-brick-info-component/manifests/android_for_quickbrick.json
> +  "name": "Info component",
done

2023-04-20 14:35 UTC, ranmeirman requested changes

2023-04-20 14:35 UTC, ranmeirman commented on plugins/quick-brick-info-component/manifests/ios_for_quickbrick.json
> +        "initial_value": false
why initial value is false? if the component is added, why do you need this flag?

2023-09-05 13:15 UTC, inckie commented
We make this plugin a data source and just use any cell style instead,

2023-09-06 09:32 UTC, closed without merging