Add parameters to youbora analytics
applicaster/Zapp-Frameworks pull request #1493
Opened 2023-05-12 07:13 UTC by ilyaKozlovApplicaster

## Description

[Monday ticket 1](https://applicaster.monday.com/boards/1615228456/views/35072856/pulses/4417260999?userId=27202915)
[Monday ticket 2](https://applicaster.monday.com/boards/1615228456/views/35072856/pulses/4417274967?userId=27202915)
[Monday ticket 3](https://applicaster.monday.com/boards/1615228456/views/35072856/pulses/4423061611?userId=27202915)

`Adding addition parameters for Analytics tracking:
app name (from Zapp)
app version (pattern "$zappVersion ($buildVersion)"
user token (on the npaw dashboard displayed as "User ID")
media id (on the npaw dashboard displayed as "Title", default lib value is stream URL)`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] iOS

</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2023-05-12 16:21 UTC, alexzchut requested changes

2023-05-12 16:21 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/Adapter/CustomAvPlayerAdapter.swift
> +    func setCustomMediaId(_ customId: String) {
no need of setter, you can access the parameter directly and set its value

2023-05-12 16:21 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/Extensions/YouboraAnalytics+PlayerObserverProtocol.swift
> +
customAdapter.customMediaId = guid

2023-05-12 16:21 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +            youboraOptions.username = userIdKey // User Id in npaw
what is npaw?

2023-05-12 16:21 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +        return "\(zappVersion)(\(appBuildVersion))"
combine guards

2023-05-12 16:21 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +    private func getAppVersionInFormat() -> String {
refactor to property **var appReleaseVersion** that returns the required value

2023-05-12 16:21 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +            youboraOptions.appName = FacadeConnector.instance?.storage?.sessionStorageValue(for: "app_name", namespace: nil) // App name in npaw
refactor to property **var appName** that returns the required value

2023-05-15 13:29 UTC, ilyaKozlovApplicaster commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +            youboraOptions.username = userIdKey // User Id in npaw
youbora analytics dashboard

2023-05-15 13:29 UTC, ilyaKozlovApplicaster commented on plugins/zapp-analytics-plugin-youbora/apple/universal/Extensions/YouboraAnalytics+PlayerObserverProtocol.swift
> +
Done

2023-05-15 13:30 UTC, ilyaKozlovApplicaster commented on plugins/zapp-analytics-plugin-youbora/apple/universal/Extensions/YouboraAnalytics+PlayerObserverProtocol.swift
> +        let customAdapter = CustomAvPlayerAdapter(player: avPlayer)
Done for guards related to getting guid value. for customAdapter we can't do it because of it's not optional.

2023-05-15 13:30 UTC, ilyaKozlovApplicaster commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +        return "\(zappVersion)(\(appBuildVersion))"
Done

2023-05-15 13:30 UTC, ilyaKozlovApplicaster commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +    private func getAppVersionInFormat() -> String {
Done

2023-05-15 13:45 UTC, alexzchut requested changes

2023-05-15 13:45 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/Extensions/YouboraAnalytics+PlayerObserverProtocol.swift
> +        let customAdapter = CustomAvPlayerAdapter(player: avPlayer)
@ilyaKozlovApplicaster combine these 2 please

2023-05-15 13:45 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +        guard let zappVersion = FacadeConnector.connector?.applicationData?.appVersion(),
please replace connector with "instance" as it is already expecting mainActor (in both places)

2023-05-16 08:30 UTC, ilyaKozlovApplicaster commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +        guard let zappVersion = FacadeConnector.connector?.applicationData?.appVersion(),
Done

2023-05-16 08:54 UTC, alexzchut approved these changes

2023-05-16 15:14 UTC, ranmeirman requested changes

2023-05-16 15:14 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +           let userIdKey = model?.configurationValue(for: Params.Plugin.userIdKey) as? String,
this is wrong. you need to pull the value of the key provided in the configuration, not the configuration value.
@alexzchut @ilyaKozlovApplicaster

2023-05-21 11:56 UTC, alexzchut requested changes

2023-05-21 11:56 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +        guard let components = userIdStorageKey?.components(separatedBy: ".") else { return "" }
@ilyaKozlovApplicaster please rewrite it to separate function that get the string and returns the tuple of key and namespace, the function will split the content as you did but also check if there are 2 elements and take first as namespace and last as key instead of [0] [1] which can fail
and unite all the guards to single one

2023-05-21 17:26 UTC, inckie commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +        guard let components = userIdStorageKey?.components(separatedBy: ".") else { return "" }
There is existing function that does it, copy it and mark for to be moved moving to the SDK (so we do not need to bump min SDK)
https://github.com/applicaster/Zapp-Frameworks/blob/master/plugins/zapp-context-setter/apple/universal/Resolvers/StorageResolver.swift

2023-06-26 05:11 UTC, ilyaKozlovApplicaster commented
Hey @ranmeirman @alexzchut can you please approve this PR? I can't merge before that.  I fixed all what you reported, also it was successfully tested and approved by customer. Thanks!

2023-06-26 05:32 UTC, alexzchut requested changes

2023-06-26 05:32 UTC, alexzchut commented on plugins/zapp-analytics-plugin-youbora/apple/universal/YouboraAnalytics.swift
> +                EventsBus.subscribe(self,
Before subscribing to specific key updates please verify it is not nil

2023-06-26 10:27 UTC, snooky23 approved these changes

2023-06-26 10:29 UTC, merged

2023-06-26 21:02 UTC, alexzchut commented
@snooky23  @ilyaKozlovApplicaster 
The function that does the split for storage parameter name and namespace has many validations and returns empty for both on failure.

If no checks are being performed before start listening to the storage key changes, it can lead in worse case to getting all storages keys changes of default or specific storage namespace.

Please add validation for empty values if key or/and namespace before subscribing to this eventbus event!