Fix/jw analytics quantile reporting
applicaster/Zapp-Frameworks pull request #1496
Opened 2023-05-15 13:21 UTC by Pretzi

## Description

[Monday ticket](add your monday ticket url here)

`If merged this will add the changes in the jwpltx file from the PR: https://github.com/jwplayer/ott-web-app/pull/256 
 the changes were tested in the TBN app and the quantile events are not being send when seeking and the ads events (impressions) are being sent to the correct endpoint
`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2023-05-15 14:08 UTC, inckie commented on plugins/zapp-analytics-plugin-jw-player/src/jwpltx.ts
> +
We probably still need these additional params (oosv, av, oaid, ppid), at least some of them were added by reqest

2023-05-15 14:26 UTC, ranmeirman requested changes

2023-05-15 14:26 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-jw-player/src/jwpltx.ts
> +  const URL = "https://ihe.jwpltx.com/v1/clienta/ping.gif?";
You should only change this on ads.

2023-05-15 20:12 UTC, Pretzi commented on plugins/zapp-analytics-plugin-jw-player/src/jwpltx.ts
> +  const URL = "https://ihe.jwpltx.com/v1/clienta/ping.gif?";
Fixed, the code from the PR  https://github.com/jwplayer/ott-web-app/pull/256 already handles this, and I verified it works as expected in the TBN app

2023-05-15 20:12 UTC, Pretzi commented on plugins/zapp-analytics-plugin-jw-player/src/jwpltx.ts
> +
Fixed

2023-06-27 13:17 UTC, inckie commented on plugins/zapp-analytics-plugin-jw-player/src/helper.ts
> +    amazon: [6, "FireOS"],
Fire TV

2023-06-27 13:17 UTC, inckie commented on plugins/zapp-analytics-plugin-jw-player/src/helper.ts
> +    lg_tv: [8, "Web OS"],
Lets ask them about that one, its not in the allowed list

2023-06-27 13:17 UTC, inckie commented on plugins/zapp-analytics-plugin-jw-player/src/helper.ts
> +    samsung_tv: [7, "Tizen OS"],
Doc says its just 'Tizen'

2023-06-27 13:17 UTC, inckie commented on plugins/zapp-analytics-plugin-jw-player/src/helper.ts
> +    ios: [2, "iOS"],
Lets ask them if they want to have iPadOS on tablets (its in the list)

2023-07-11 13:16 UTC, inckie approved these changes

2023-07-11 14:23 UTC, ranmeirman approved these changes

2023-07-11 14:24 UTC, merged