Feat/appflyer ctv platforms
applicaster/Zapp-Frameworks pull request #1552
Opened 2023-07-19 13:32 UTC by Pretzi

## Description

[Monday ticket](add your monday ticket url here)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2023-07-20 08:37 UTC, ranmeirman requested changes

2023-07-20 13:25 UTC, inckie commented on plugins/zapp-analytics-plugin-appsflyer/src/index.ts
> +  const isFirstAppOpenDispatched = await getFromLocal("isFirstAppOpenDispatched");
Extract constant and use it in both places, you set one value, but check another value

2023-07-20 13:27 UTC, inckie commented on plugins/zapp-analytics-plugin-appsflyer/src/index.ts
> +    const eventName = "first_open";
remove this value override and if above, keep function itself correct, higher levels decide what to send

2023-07-20 13:45 UTC, Pretzi commented on plugins/zapp-analytics-plugin-appsflyer/src/index.ts
> +  const isFirstAppOpenDispatched = await getFromLocal("isFirstAppOpenDispatched");
Fixed

2023-07-20 13:46 UTC, Pretzi commented on plugins/zapp-analytics-plugin-appsflyer/src/index.ts
> +  sendEvent,
Fixed

2023-07-20 13:46 UTC, Pretzi commented on plugins/zapp-analytics-plugin-appsflyer/src/index.ts
> +  const isFirstAppOpenDispatched = await getFromLocal("isFirstAppOpenDispatched");
Fixed

2023-07-20 13:47 UTC, Pretzi commented on plugins/zapp-analytics-plugin-appsflyer/src/index.ts
> +    const eventName = "first_open";
Fixed

2023-07-20 19:47 UTC, inckie commented on plugins/zapp-analytics-plugin-appsflyer/src/index.ts
> +  setInLocalStorage(IS_FIRST_APP_OPEN_DISPATCHED, true);
Move flag setter below if check, otherwise if config was not initially provided, we will never sent the event, even if customer fixes the plugin config.
Also lets parse and validate
const url = pluginConfiguration?.first_open_feed?.source;
there, for the same reason, and return error if url is not configured

2023-07-21 18:02 UTC, Pretzi commented on plugins/zapp-analytics-plugin-appsflyer/src/index.ts
> +  setInLocalStorage(IS_FIRST_APP_OPEN_DISPATCHED, true);
Fixed

2023-07-26 18:25 UTC, inckie approved these changes

2023-07-28 13:56 UTC, ranmeirman approved these changes

2023-07-28 16:12 UTC, merged