fix(login-flow, login-oauth-tv-2.0): toggle for displaying logo on auth flow screens
applicaster/Zapp-Frameworks pull request #1569
Opened 2023-08-14 14:29 UTC by kviktorchik-sc

## Description

[Pureflix - [AMIL-471] [STV] - Login - Activation Code Page Unbranded](https://applicaster.monday.com/boards/1615228456/pulses/4528668228)

Added a control to enable a logo image on web login flow screens.
Related PR: https://github.com/applicaster/web-login-flow/pull/86

<details>
  <summary>Platforms Affected</summary>
  
- [x] Android
- [x] Android TV
- [x] Apple TV (TVOS)
- [x] Fire TV (FireOS)
- [x] iOS
- [x] LG TV (WebOS)
- [x] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2023-08-14 15:31 UTC, ranmeirman requested changes

2023-08-14 15:31 UTC, ranmeirman commented on plugins/quick-brick-login-flow/manifests/manifest.config.js
> +          key: "show_intro_asset",
@kviktorchik-sc this is problematic.
currently we have the logo on the intro, and it should be by default there (all our current apps use this log).
We should have a separate key to show logo on all screen, the intro shouldn't be configurable, it should always have the logo.

2023-08-15 08:25 UTC, kviktorchik-sc commented on plugins/quick-brick-login-flow/manifests/manifest.config.js
> +          key: "show_intro_asset",
@ranmeirman This option isn't used to configure the Intro screen. It's named like this to match the logo image key - `intro_asset`, but we can use another value. `show_logo`, for example

2023-08-15 12:41 UTC, ranmeirman approved these changes

2023-08-21 13:05 UTC, inckie approved these changes

2023-08-21 13:05 UTC, merged