refactor(matchbox-plugin):changing api upperCase fields to lowerCase
applicaster/Zapp-Frameworks pull request #1592
Opened 2023-09-06 12:54 UTC by AshotManukyan

## Description

[Monday ticket](https://applicaster.monday.com/boards/1615228456/pulses/5106153946)

Changed all the fields that started with a capital letter to be lowerCase

<details>
  <summary>Platforms Affected</summary>
  
- [x] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [x] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2023-09-06 20:26 UTC, snooky23 requested changes

2023-09-06 20:26 UTC, snooky23 commented on plugins/quick-brick-matchbox/README.md
> +    4. `placeOfGameHeb`;
should be placeOfGame without Heb

2023-09-06 20:26 UTC, snooky23 commented on plugins/quick-brick-matchbox/src/components/MatchBoxItem.js
> +const placeOfGameHeb = extensions?.PlaceOfGameHeb || extensions?.placeOfGameHeb;
remove the Heb

2023-09-06 20:26 UTC, snooky23 commented on plugins/quick-brick-matchbox/src/utils/consts.js
> +export const BOARD_ID = 5;
What the number represent?

2023-09-06 21:00 UTC, AshotManukyan commented on plugins/quick-brick-matchbox/src/utils/consts.js
> +export const BOARD_ID = 5;
This was hardcoded in MatchboxItem component like this
`{Number(extensions?.BOARD_ID) === 5 && (
              <Text
                style={styles.gameTitle}
              >{`${localization?.gameNumber} ${extensions?.gameNumber}`}</Text>
            )}`
so I removed from render and placed it in constants

2023-09-07 12:21 UTC, snooky23 approved these changes

2023-09-11 09:18 UTC, merged