fix: new url handling approach
applicaster/Zapp-Frameworks pull request #316
Opened 2021-05-24 18:14 UTC by inckie

Use new way for registering url scheme handlers to open internal native screens.

2021-05-24 18:48 UTC, inckie commented
@f-roland @Budaa Please review, I'm a bit uncomfortable with having fields inside the function I export, but maybe its ok. Since I have both React screen and special handlers in the same plugin. But maybe its normal approach.
Also please review my note about better error handling.

2021-05-24 19:28 UTC, Budaa approved these changes
LGTM :+1:
Thanks for pointing out the issue with error handling. We're aware of it and I believe is on the TODO list, after project alpha.

2021-05-24 19:38 UTC, inckie commented
@Budaa 
This is how it can look like, Sherwin built that awesome screen. Very good for release managers and non js developers.
![didomiErrorScreen](https://user-images.githubusercontent.com/2348227/113514374-1a7e6700-953c-11eb-90f8-9c8f9a7bf4a2.jpg)

2021-05-24 19:40 UTC, Budaa commented
@inckie I tought you're talking about general error handling. Yes, I agree, there should be better error handling for this feature and it definitely shouldn't lock you out from the app like that... We will have look.

2021-05-25 07:42 UTC, f-roland requested changes
adding props to the StatsScreen export is fine

As @Budaa explained we know we need to work on our error screen. This has been in the backlog for a while. We'll look into it.

I thought we already had a mecanism to send home when a scheme couldn't be resolved, but apparently not, at least not for schemes created from plugins (which you're the first one to use)

That, we can add

Please check the API doc I added in the comments to see how to invoke the `onFinish` function. I think this isn't final as the hook isn't doing anything for now ?

2021-05-25 07:42 UTC, f-roland commented on plugins/quick-brick-opta-stats/src/index.js
> +export default StatScreens = ({ screenData }: Props) => {
what is this `screenData` prop ? it's not being passed to anything here

2021-05-25 07:42 UTC, f-roland commented on plugins/quick-brick-opta-stats/src/index.js
> +useUrlSchemeHandler = async ({ query, url, onFinish }) => {
Have a look here: https://github.com/applicaster/developer-docs-3/pull/80/files

this isn't published yet, but it explains the API to use for the hook.
`onFinish` should be invoked with a callback, calling the `done` function

```
onFinish((done) => {
   // navigation, any other action here...
   done();
});

2021-05-25 07:42 UTC, f-roland commented on plugins/quick-brick-opta-stats/src/index.js
> +StatScreens.urlScheme = {
this is fine. in JS everything is an object, even functions. so you can add properties to them

2021-05-25 16:48 UTC, inckie commented on plugins/quick-brick-opta-stats/src/index.js
> +useUrlSchemeHandler = async ({ query, url, onFinish }) => {
added the callback

2021-05-25 16:51 UTC, inckie commented
> Please check the API doc I added in the comments to see how to invoke the `onFinish` function. I think this isn't final as the hook isn't doing anything for now ?

Hook is opening a native screen as a new activity. It's was the desired approach there and in Didomi plugin: call a native method and wait for the result without any additional screens or navigation in the QB app.

2021-05-26 07:34 UTC, f-roland reviewed
I see.
Did we test what happens when a user wants to leave these screens ? are you getting back to the home screen ? an empty screen ? 

With the approach you describe, basically it's like you are opening a new app, so I'm not sure what the user experience will be when the user is pressing the back button from this screen

2021-05-26 13:28 UTC, inckie commented
@f-roland app loads to the home screen first in any case, and only then url processing happens, so when you navigate back, you get to the original state.

2021-05-26 14:08 UTC, f-roland commented
alright, looks good then

2021-05-26 14:17 UTC, f-roland approved these changes

2021-05-26 14:47 UTC, kononenkoAnton approved these changes

2021-05-26 14:48 UTC, merged