Fix/inplayer faulty deps
applicaster/Zapp-Frameworks pull request #433
Opened 2021-08-04 14:15 UTC by Pretzi

If merged this will fix the issue of the failing builds in the web platforms

2021-08-04 18:31 UTC, kononenkoAnton requested changes

2021-08-04 18:31 UTC, kononenkoAnton commented on plugins/quick-brick-inplayer-login/src/Services/inPlayerService.js
> +    logger.debug({
Please change logger to error and probably throw the error after log

2021-08-05 12:20 UTC, Pretzi commented on plugins/quick-brick-inplayer-login/src/Services/inPlayerService.js
> +    logger.debug({
Done

2021-08-05 13:40 UTC, kononenkoAnton approved these changes

2021-08-05 13:42 UTC, merged