Feat/iai analytics plugin
applicaster/Zapp-Frameworks pull request #549
Opened 2021-11-12 02:56 UTC by Pretzi

If merged this will add the IAI Analytic plugin.

2021-11-12 03:19 UTC, ranmeirman requested changes

2021-11-12 03:19 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-iai/src/components/Analytics.tsx
> +        fb: await getFbToken(fbTokenKey, fbNamespace),
@Pretzi  let's use Promise.all

2021-11-12 03:19 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-iai/src/components/Analytics.tsx
> +      if (res.status !== 200 || !res.data.isSuccessStatusCode) {
Response could be 20x and 30x and still succesful. You should check > 400 or something similar

2021-11-12 06:09 UTC, Pretzi commented on plugins/zapp-analytics-plugin-iai/src/components/Analytics.tsx
> +        fb: await getFbToken(fbTokenKey, fbNamespace),
Done 👍

2021-11-12 06:09 UTC, Pretzi commented on plugins/zapp-analytics-plugin-iai/src/components/Analytics.tsx
> +      if (res.status !== 200 || !res.data.isSuccessStatusCode) {
Done 👍

2021-11-12 06:12 UTC, ranmeirman reviewed
@Pretzi Code looks good. Have you tested it on device?

2021-11-12 06:16 UTC, Pretzi commented
> @Pretzi Code looks good. Have you tested it on device?

Only on the android simulator

2021-11-23 23:40 UTC, ranmeirman requested changes

2021-11-23 23:40 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-iai/manifests/android_for_quickbrick.json
> +      "key": "service_url",
@Pretzi Lets add initial values for all fields please, so there is no need to fill it

2021-11-23 23:40 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-iai/src/utils/index.ts
> +  const accessToken = await localStorage.getItem(key, namespace);
I suggest to use CTX manager instead of explicit local or session storage.
@inckie what do you think?

2021-11-23 23:40 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-iai/src/utils/index.ts
> +  const fbToken = await localStorage.getItem(key, namespace);
Same as above

2021-11-24 00:55 UTC, Pretzi commented on plugins/zapp-analytics-plugin-iai/src/utils/index.ts
> +  const accessToken = await localStorage.getItem(key, namespace);
@ranmeirman not sure what you mean by using the CTX manager, can you point me to an example?

2021-11-24 00:58 UTC, Pretzi commented on plugins/zapp-analytics-plugin-iai/manifests/android_for_quickbrick.json
> +      "key": "service_url",
Done

2021-11-24 01:12 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-iai/src/utils/index.ts
> +  const accessToken = await localStorage.getItem(key, namespace);
https://docs.applicaster.com/plugin-development/30-guides/70-quick-brick-apis/45-context-keys-manager/#gdpr

2021-11-24 12:46 UTC, alexzchut requested changes

2021-11-24 12:46 UTC, alexzchut commented on plugins/zapp-analytics-plugin-iai/manifests/manifest.config.js
> +      initial_value: "https://iaimobile-weareiai.azurewebsites.net/api/SaveVersion?code=JtWROrjDkvnfOWsYiw/q4tciwfiFdcJV1fmzgF/Ix2KYLIALwF4yNw==",
if this suppose to be generic plugin, please remove customer related url from initial value

2021-11-24 12:51 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-iai/manifests/manifest.config.js
> +      initial_value: "https://iaimobile-weareiai.azurewebsites.net/api/SaveVersion?code=JtWROrjDkvnfOWsYiw/q4tciwfiFdcJV1fmzgF/Ix2KYLIALwF4yNw==",
It is not general, it is customer specific

2021-11-24 12:53 UTC, alexzchut commented on plugins/zapp-analytics-plugin-iai/manifests/manifest.config.js
> +      initial_value: "https://iaimobile-weareiai.azurewebsites.net/api/SaveVersion?code=JtWROrjDkvnfOWsYiw/q4tciwfiFdcJV1fmzgF/Ix2KYLIALwF4yNw==",
@ranmeirman if it custom specific it probably should not be in this repo

2021-11-24 12:54 UTC, ranmeirman requested changes
@Pretzi the customer says that it get stuck on the analytics plugin screen on iOS. Could you please check and fix asap?

2021-11-24 12:58 UTC, ranmeirman commented on plugins/zapp-analytics-plugin-iai/manifests/manifest.config.js
> +      initial_value: "https://iaimobile-weareiai.azurewebsites.net/api/SaveVersion?code=JtWROrjDkvnfOWsYiw/q4tciwfiFdcJV1fmzgF/Ix2KYLIALwF4yNw==",
There are few plugins which are customer specific here. We will probably need to build a new mono repo for custom plugins.

2021-11-24 13:26 UTC, Pretzi commented
> @Pretzi the customer says that it get stuck on the analytics plugin screen on iOS. Could you please check and fix asap?

It was an issue in previous canary version

2021-12-02 21:36 UTC, ranmeirman commented
@Pretzi let's not keep PR open that much, let's merge and if needed open a new pr

2021-12-03 01:15 UTC, ranmeirman approved these changes

2021-12-06 15:15 UTC, alexzchut requested changes

2021-12-06 15:15 UTC, alexzchut commented on plugins/zapp-analytics-plugin-iai/manifests/manifest.config.js
> +  ios_for_quickbrick: "0.1.0-alpha1",
lets put min sdk based on latest stable version - **5.5.0-Dev**
if you think there is a code requires next release so better to put - **5.6.0-Dev**

2021-12-07 04:00 UTC, Pretzi commented on plugins/zapp-analytics-plugin-iai/manifests/manifest.config.js
> +  ios_for_quickbrick: "0.1.0-alpha1",
@alexzchut  Done 👍

2021-12-07 14:57 UTC, alexzchut approved these changes

2021-12-07 14:58 UTC, merged