feat(zapp_login_plugin_oauth_tv_2_0): add logout confirmation screen
applicaster/Zapp-Frameworks pull request #707
Opened 2022-01-18 14:43 UTC by alashuk-sc

## Description: 
Add Logout confirmation screen.

### Ticket: 
https://applicaster.monday.com/boards/1615228456/views/35072856/pulses/2123873478?userId=17198506

2022-01-20 19:12 UTC, kononenkoAnton approved these changes

2022-01-20 19:15 UTC, ranmeirman requested changes

2022-01-20 19:15 UTC, ranmeirman commented on plugins/zapp_login_plugin_oauth_tv_2_0/manifests/localizations.config.js
> +    key: "cancel_sing_out",
typo - sing-sign

2022-01-20 19:15 UTC, ranmeirman commented on plugins/zapp_login_plugin_oauth_tv_2_0/manifests/localizations.config.js
> +    key: "sing_out_title",
typo

2022-01-21 07:42 UTC, alashuk-sc commented on plugins/zapp_login_plugin_oauth_tv_2_0/manifests/localizations.config.js
> +    key: "cancel_sing_out",
fixed

2022-01-21 07:42 UTC, alashuk-sc commented on plugins/zapp_login_plugin_oauth_tv_2_0/manifests/localizations.config.js
> +    key: "sing_out_title",
fixed

2022-01-21 09:01 UTC, snooky23 approved these changes

2022-01-21 11:21 UTC, merged