Update x-ray README.md for Android
applicaster/Zapp-Frameworks pull request #72
Opened 2020-09-23 21:58 UTC by inckie

Add url scheme instructions

2020-09-23 22:28 UTC, ranmeirman requested changes

2020-09-23 22:28 UTC, ranmeirman commented on plugins/quick-brick-xray/README.md
> +Example url: ```wino://xray?shortcutEnabled=true&crashReporting=true&reactNativeLogLevel=info```
Isn't it the same for ios?

2020-09-23 22:39 UTC, inckie commented on plugins/quick-brick-xray/README.md
> +Example url: ```wino://xray?shortcutEnabled=true&crashReporting=true&reactNativeLogLevel=info```
iOS has less options, I'll ask Anton to add it

2020-09-24 15:00 UTC, ranmeirman approved these changes

2020-09-24 15:01 UTC, merged