chore(inplayer-login): add login data extension
applicaster/Zapp-Frameworks pull request #752
Opened 2022-02-15 20:52 UTC by Pretzi

## Description

[Monday ticket](add your monday ticket url here)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2022-02-16 15:48 UTC, kononenkoAnton requested changes

2022-02-16 15:48 UTC, kononenkoAnton commented on plugins/quick-brick-inplayer-login/runInBackground.js
> +    const newPayload = {
@Pretzi We will have crash if extensions will be null

2022-02-17 15:22 UTC, Pretzi commented on plugins/quick-brick-inplayer-login/runInBackground.js
> +    const newPayload = {
It shouldn't crash but I added an empty object as a fallback for the item.extensions

2022-02-17 15:23 UTC, kononenkoAnton approved these changes

2022-02-17 15:24 UTC, merged