Feat/storefront unified
applicaster/Zapp-Frameworks pull request #788
Opened 2022-03-11 19:35 UTC by Budaa

## Description

[Monday ticket](add your monday ticket url here)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2022-03-17 01:43 UTC, ranmeirman requested changes
Overall looks good. One major issue here is to use pipes client, this is required as other vendors will require other keys. In addition it will remove a lot of code.

2022-03-17 01:43 UTC, ranmeirman commented on plugins/quick-brick-storefront/src/Storefront/Storefront.ts
> +    const { data: offers } = await axios.get(url);
This should use pipes client. This will avoid the need to hard code fetch with tokens. All app requests in general should be using pipes client as it add the ctx by default @Budaa @aborisenko-sc @f-roland

2022-03-17 01:43 UTC, ranmeirman commented on plugins/quick-brick-storefront/src/Storefront/Storefront.ts
> +  private generateUrl(offersUrl, token) {
As I wrote above using pipes client remove the need for all this code including the token fetchig

2022-03-22 21:18 UTC, kononenkoAnton approved these changes

2022-03-23 02:05 UTC, ranmeirman requested changes

2022-03-23 02:05 UTC, ranmeirman commented on plugins/quick-brick-storefront/src/utils/validationHelper.ts
> +      store: store,
Please add `platform`

2022-03-24 16:35 UTC, merged