Add mapping for data sources
applicaster/Zapp-Frameworks pull request #823
Opened 2022-03-28 15:52 UTC by kononenkoAnton

## Description

[Monday ticket](add your monday ticket url here)

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2022-03-28 23:58 UTC, ranmeirman requested changes

2022-03-28 23:58 UTC, ranmeirman commented on plugins/quick-brick-login-flow/src/Services/localStorageService.ts
> +const emailKey = "user_id";
Why not username?

2022-03-29 00:02 UTC, kononenkoAnton commented on plugins/quick-brick-login-flow/src/Services/localStorageService.ts
> +const emailKey = "user_id";
because it can be email as well

2022-03-29 00:03 UTC, kononenkoAnton commented on plugins/quick-brick-login-flow/src/Services/localStorageService.ts
> +const emailKey = "user_id";
@ranmeirman do you want me to change to username?\

2022-03-29 00:11 UTC, ranmeirman commented on plugins/quick-brick-login-flow/src/Services/localStorageService.ts
> +const emailKey = "user_id";
I think we should, no?

2022-03-29 00:13 UTC, kononenkoAnton commented on plugins/quick-brick-login-flow/src/Services/localStorageService.ts
> +const emailKey = "user_id";
ok, will change. I think about something more general

2022-03-29 18:50 UTC, merged