feat: Adding support of Async/Await for plugins loading
applicaster/Zapp-Frameworks pull request #857
Opened 2022-04-11 16:50 UTC by alexzchut

Adding support of Async/Await for plugins loading

- preparing the structure
- adding support for plugins
- - Analytics plugins: Airship, Mixpanel, Firebase
- - Push plugins: Airship

`Please describe PR here`

<details>
  <summary>Platforms Affected</summary>
  
- [ ] Android
- [ ] Android TV
- [ ] Apple TV (TVOS)
- [ ] Fire TV (FireOS)
- [ ] iOS
- [ ] LG TV (WebOS)
- [ ] Samsung TV (Tizen)
- [ ] Web
</details>

## Known or Pending Issues

`fill in this section with potential issues / limitations the reviewer(s) should know about`

## Screenshots

`If there is some kind of ui change please share screenshots`

## Version Info

`Does this update require a certain version of quickbrick, or does it rely on another pr to work?`

2022-04-13 16:39 UTC, kononenkoAnton approved these changes

2022-04-17 09:31 UTC, alexzchut commented on plugins/zapp-apple/apple/universal/Plugins/PluginManagerBase/PluginManagerBase.swift
> +        if let provider = provider as? AsyncPluginAdapterProtocol,
This is the switch to new implementation and fallback if not implemented

2022-04-17 11:43 UTC, snooky23 requested changes

2022-04-17 11:43 UTC, snooky23 commented on plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +            requestTrackingAuthorization { _ in
And if you want to do the UI update on the main thread, rather than dispatching it back to the main queue, you would simply add the @MainActor modifier to the method that requests the ad.

2022-04-17 11:43 UTC, snooky23 commented on plugins/zapp-analytics-plugin-airship/apple/universal/AnalyticsProviderAirship.swift
> +        super.prepareProvider(defaultParams, completion: completion)
in addition to the @MainActor pattern shown above (as a replacement for dispatching to the main queue), you can also do the:

```
await MainActor.run {
    ...
}
```

2022-04-17 11:43 UTC, snooky23 commented on plugins/zapp-analytics-plugin-firebase/apple/ios/APAnalyticsProviderFirebase.swift
> +        guard let path = Bundle.main.path(forResource: "GoogleService-Info",
Please const the resource `GoogleService-Info`

2022-04-18 19:22 UTC, alexzchut commented on plugins/zapp-analytics-plugin-airship/apple/universal/AnalyticsProviderAirship.swift
> +        super.prepareProvider(defaultParams, completion: completion)
this part is related to devices below 15 so needs to kept as is.

2022-04-18 19:22 UTC, alexzchut commented on plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
> +            requestTrackingAuthorization { _ in
this part is related to devices below 15 so needs to kept as is.

2022-04-24 19:01 UTC, snooky23 requested changes

2022-04-26 13:18 UTC, snooky23 commented on plugins/zapp-apple/apple/universal/RootController/RootController+AppLoadingStateMachineDataSource.swift
>              DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
I don't like this time...

2022-04-26 13:21 UTC, snooky23 commented on plugins/applicaster-di-manager/apple/universal/ZPDiManager.swift
>              DispatchQueue.main.async {
Task.detached ..

2022-04-26 13:25 UTC, snooky23 commented on plugins/zapp-push-plugin-urban-airship/apple/ios/APPushProviderUrbanAirship.swift
>          DispatchQueue.main.async {
same

2022-04-28 06:26 UTC, alexzchut commented on plugins/quick-brick-google-ima-apple/apple/universal/GoogleInteractiveMediaAdsAdapter/GoogleInteractiveMediaAdsAdapter.swift
>                      self.requestAd(with: self.imaConfig, player: player)
I am not moving this to async, just adding new initialization functions where it possible, the logic and implementation of the plugin stands as it, until we can completely switch to async

2022-04-28 06:27 UTC, alexzchut commented on plugins/zapp-apple/apple/universal/RootController/RootController+AppLoadingStateMachineDataSource.swift
>              DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
Me too but this will remain for now, not touching current implementation

2022-04-28 06:28 UTC, alexzchut commented on plugins/zapp-push-plugin-urban-airship/apple/ios/APPushProviderUrbanAirship.swift
>          DispatchQueue.main.async {
older prepare functions will remain for use by older devices or older iOS versions that can not use async functions

2022-04-28 06:28 UTC, alexzchut commented on plugins/zapp-push-plugin-firebase/apple/ios/APPushProviderFirebase.swift
>                  DispatchQueue.main.async {
the logic and implementation of the plugin stands as it, until we can completely switch to async

2022-04-28 06:30 UTC, alexzchut commented on plugins/zapp-analytics-plugin-airship/apple/universal/AnalyticsProviderAirship.swift
>          DispatchQueue.main.async {
the logic and implementation of the plugin stands as it for use of older devices and older os versions, until we can completely switch to async

2022-04-28 06:30 UTC, alexzchut commented on plugins/applicaster-di-manager/apple/universal/ZPDiManager.swift
>              DispatchQueue.main.async {
the logic and implementation of the plugin stands as it for use of older devices and older os versions, until we can completely switch to async

2022-05-01 10:55 UTC, merged